"use client"

import { Button } from "@/components/ui/button"
import { Download } from "lucide-react"
import type { Patient } from "@/lib/types"

interface PDFDownloadButtonProps {
  patient: Patient
}

export function PDFDownloadButton({ patient }: PDFDownloadButtonProps) {
  const handleDownload = () => {
    // Create PDF content
    const pdfContent = `
VITALWAVE - TRIP SUMMARY REPORT
================================

Patient Information:
-------------------
Patient ID: ${patient.patientId}
Name: ${patient.name || "N/A"}
Age: ${patient.age || "N/A"}
Gender: ${patient.gender || "N/A"}

Medical Details:
---------------
Initial Diagnosis: ${patient.initialDiagnosis || "N/A"}
Additional Notes: ${patient.notes || "N/A"}

Vital Signs (Last Reading):
---------------------------
Heart Rate: ${patient.vitals.heartRate} bpm
SpO2: ${patient.vitals.spo2}%
Last Updated: ${new Date(patient.vitals.timestamp).toLocaleString()}

Trip Information:
----------------
Status: ${patient.status}
Ambulance ID: ${patient.ambulanceId}
${patient.tripStartTime ? `Trip Start: ${new Date(patient.tripStartTime).toLocaleString()}` : ""}
${patient.tripEndTime ? `Trip End: ${new Date(patient.tripEndTime).toLocaleString()}` : ""}
${patient.distance ? `Distance: ${patient.distance.toFixed(1)} km` : ""}
${patient.eta ? `ETA: ${patient.eta} minutes` : ""}

Report Generated: ${new Date().toLocaleString()}
Generated by: VitalWave Platform
    `.trim()

    // Create blob and download
    const blob = new Blob([pdfContent], { type: "text/plain" })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `trip-summary-${patient.patientId}-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    window.URL.revokeObjectURL(url)
  }

  return (
    <Button onClick={handleDownload} variant="outline" size="sm">
      <Download className="h-4 w-4 mr-2" />
      Download Trip Summary
    </Button>
  )
}
